<?php
/**
 * Front-end performance: disable Twemoji, preload critical fonts.
 *
 * @package Jardin
 */

defined( 'ABSPATH' ) || exit;

/**
 * Remove WordPress emoji scripts, styles and filters.
 *
 * Modern browsers render emoji natively; the Twemoji pipeline adds
 * a render-blocking JS + CSS pair and an external DNS lookup to s.w.org.
 */
function jardin_disable_emoji(): void {
	remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
	remove_action( 'wp_print_styles', 'print_emoji_styles' );
	remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
	remove_action( 'admin_print_styles', 'print_emoji_styles' );
	remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
	remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );
	remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );

	add_filter( 'tiny_mce_plugins', 'jardin_disable_emoji_tinymce' );
	add_filter( 'wp_resource_hints', 'jardin_remove_emoji_dns_prefetch', 10, 2 );
}
add_action( 'init', 'jardin_disable_emoji' );

/**
 * Strip the wpemoji TinyMCE plugin.
 *
 * @param array $plugins TinyMCE plugin list.
 * @return array
 */
function jardin_disable_emoji_tinymce( $plugins ) {
	if ( ! is_array( $plugins ) ) {
		return array();
	}
	return array_diff( $plugins, array( 'wpemoji' ) );
}

/**
 * Drop the s.w.org DNS-prefetch added for Twemoji SVGs.
 *
 * @param array  $urls          Resource hint URLs.
 * @param string $relation_type Hint type (dns-prefetch, preconnect…).
 * @return array
 */
function jardin_remove_emoji_dns_prefetch( array $urls, string $relation_type ): array {
	if ( 'dns-prefetch' !== $relation_type ) {
		return $urls;
	}

	$emoji_url = apply_filters( 'emoji_svg_url', 'https://s.w.org/images/core/emoji/2/svg/' );

	return array_values(
		array_filter(
			$urls,
			static function ( $url ) use ( $emoji_url ) {
				return false === strpos( (string) $url, wp_parse_url( $emoji_url, PHP_URL_HOST ) );
			}
		)
	);
}

/**
 * Preload the body font (Inter variable) to minimise the swap flash.
 *
 * Only the single woff2 used above the fold is preloaded; heading and
 * mono fonts load normally via the @font-face generated by theme.json.
 */
function jardin_preload_fonts(): void {
	if ( is_admin() ) {
		return;
	}

	$href = get_template_directory_uri() . '/assets/fonts/inter-variable.woff2';

	printf(
		'<link rel="preload" href="%s" as="font" type="font/woff2" crossorigin>' . "\n",
		esc_url( $href )
	);
}
add_action( 'wp_head', 'jardin_preload_fonts', 1 );
